/* =========================================================
   SITE CONFIG
   -----------------------------------------------------------
   AUTO-GENERATED by the admin server every time you save your
   WhatsApp number, message, email or address — do not edit this
   file by hand, your changes will be overwritten on the next
   save. Make changes in the admin panel (/admin/) instead.
   ========================================================= */

const SITE = {
  "name": "Alfareed Traders",
  "currencySymbol": "Rs. ",
  "whatsappNumber": "923390110342",
  "whatsappMessage": "Hi Alfareed Traders, I'd like to know more about your flour products.",
  "phoneDisplay": "+92 339 0110342",
  "email": "alfareed.pk@gmail.com",
  "address": "Alfareed Traders, 27-Km,Feroze pur Road Soa Asal,Lahore",
  "facebook": "https://facebook.com/",
  "instagram": "https://www.instagram.com/alfareed.pk/"
};

function whatsappGeneralLink() {
  const msg = SITE.whatsappMessage || `Hi ${SITE.name}, I'd like to know more about your products.`;
  return `https://wa.me/${SITE.whatsappNumber}?text=${encodeURIComponent(msg)}`;
}
