/* =========================================================
   SITE CONFIG
   -----------------------------------------------------------
   AUTO-GENERATED by the admin server every time you save your
   WhatsApp number, message, email or address — do not edit this
   file by hand, your changes will be overwritten on the next
   save. Make changes in the admin panel (/admin/) instead.
   ========================================================= */

const SITE = {
  "name": "Alfareed Traders",
  "currencySymbol": "Rs. ",
  "whatsappNumber": "923001234567",
  "whatsappMessage": "Hi Alfareed Traders, I'd like to know more about your flour products.",
  "phoneDisplay": "+92 300 1234567",
  "email": "orders@alfareedtraders.com",
  "address": "Alfareed Traders, Grain Market Road, Lahore, Pakistan",
  "facebook": "https://facebook.com/",
  "instagram": "https://instagram.com/"
};

function whatsappGeneralLink() {
  const msg = SITE.whatsappMessage || `Hi ${SITE.name}, I'd like to know more about your products.`;
  return `https://wa.me/${SITE.whatsappNumber}?text=${encodeURIComponent(msg)}`;
}
